name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Configure
      run: mkdir build && cd build && cmake ..

    - name: Build
      run: cd build && cmake --build .

    - name: Test
      run: cd build && ctest
